### ISSUE TITLE
Releasing binaries

### ISSUE THREAD

**Issue by AppIns** [popwser/Storyboard#15]
To release binaries, click [here](https://github.com/popwser/Storyboard/releases) and add a new release, then select a binary and add it with the release. Make sure you name them so people know how to execute them, like "storyboard-windows.exe", "storyboard-osx", and "storyboard-linux." I primarily use linux so I'll compile that for you

**Comment by popwser** [comment]
Thanks, I will compile the OSX binaries and the windows ones too (I have a windows laptop I can use)
