### ISSUE TITLE
Serious issue in standard.hpp

### ISSUE THREAD

**Issue by AppIns** [popwser/Storyboard#17]
So I was able to compile everything but not without taking out this line

```c++
    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
```
I decided I would put the errors in a .txt file, so [here!](https://github.com/popwser/Storyboard/files/431807/dump.txt)

I also have that Linux binary ready, but obviously this line might be important

**Comment by popwser** [comment]
I am not able to reproduce this, everything compiles fine for me, I also need that to work with CIN errors properly

**Comment by AppIns** [comment]
Are you comparing 2 values with std::max?

**Comment by popwser** [comment]
`std::numeric_limits<std::streamsize>::max()` is the max size a stream can be I am pretty sure, max should be returning that value

**Comment by AppIns** [comment]
Where is std::numeric_limits, is that in a header file?

**Comment by popwser** [comment]
just google this stuff, you'll find the specifics, it's part of the standard library though

**Comment by popwser** [comment]
it seems I can't reproduce this, sorry it doesn't work for you, i'll ask some other people to test it and see what they get then reopen this if needed

**Comment by AppIns** [comment]
I'll try 
'''c++
#include <limits>
'''
 and see if that helps

**Comment by popwser** [comment]
it's fixed, btw, pull the changes
